import type { Metadata } from "next";
import { Oswald, Nunito } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/theme/theme-provider";
import { AuthProvider } from "@/context/authContext";
import Providers from "@/context/queryProvider";
import { NotificationProvider } from "@/context/NotificationProvider";

const OswaldSans = Oswald({
  variable: "--font-oswald",
  weight: ["200", "300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

const MerriweatherSans = Nunito({
  variable: "--font-nunito",
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning >
      <body
        className={`${OswaldSans.variable} ${MerriweatherSans.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NotificationProvider>
            <Providers>
              <AuthProvider>
                {children}
              </AuthProvider>
            </Providers>
          </NotificationProvider>
        </ThemeProvider>

      </body>
    </html>
  );
}
